version: 0.4.0

logging_level: INFO

results_dir: 'results/'
summary_dir: results
costs_dir: '../technology-data/outputs/'
run: 'weatheryears_hourly' #_simple_weather' # use this to keep track of runs with different settings
foresight: 'overnight' # options are overnight, myopic, perfect (perfect is not yet implemented)
# if you use myopic or perfect foresight, set the investment years in "planning_horizons" below

scenario:
  sectors: [E]  # ignore this legacy setting
  simpl: [370]  # only relevant for PyPSA-Eur # Can maybe be used for year
  year: [1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013]
  clusters: [74] #,74] #,74,111,148] #,185,222,259] # number of nodes in Europe, any integer between 37 (1 node per country-zone) and several hundred
  lv: [1.0]
  opts: ['']
                    # aCAES  #LAES # TES   # PTES  # MSES # RFB  # H2 
  charge_e: [1.540] #[1.840, 1.540, 1.960, 4.400, 1.980, 1.700, 1.360] #[0.600,0.800,1.000,1.100,1.200,1.300,1.400,1.500,1.700,1.900,2.000,2.500,3.000,3.500,4.000] # [0.500,1.000,1.900,4]
  charge_c: [1.670] #[0.930, 1.670, 0.110, 0.970, 0.310, 0.520, 1.340] #[0.100,0.200,0.300,0.400,0.500,0.600,0.700,0.800,0.900,1.000,1.400,2.000] # [0.100,1.000,1.400,2.000]
  discharge_e: [1.300] #[1.300, 1.300, 0.760, 0.500, 0.860, 1.700, 1.000] #[0.600,0.800,1.000,1.100,1.200,1.300,1.400,1.500,1.700,1.900,2.000] # [0.500,1.000,1.900]
  discharge_c: [1.670] #[1.870, 1.670, 2.570, 1.940, 3.090, 0.520, 3.270] #[0.100,0.200,0.300,0.400,0.500,0.600,0.700,0.800,0.900,1.000,1.400,2.000] # [0.100,1.000,1.400,2.000]
  storage_c: [1.600] #[1.350, 1.600, 0.400, 1.000, 0.900, 6.000, 0.550] #[0.010,0.050,0.100,0.150,0.200,0.250,0.300,0.400,0.500,0.600,0.700,0.800,0.900,1.000,1.500,2.000,4.000] # [0.050,0.100,0.250,0.500,1.000,1.500,2.000] [0.050,0.100,0.250,0.500,1.000,1.500,2.000]
  sloss: [30] #[2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,35,40,45,50,55,60] #[10,30] 
  sector_opts: [Co2L0-1H-solar+p3-dist1]

  # Co2Lx specifies the CO2 target in x% of the 1990 values; default will give default (5%);
  # Co2L0p25 will give 25% CO2 emissions; Co2Lm0p05 will give 5% negative emissions
  # xH is the temporal resolution; 3H is 3-hourly, i.e. one snapshot every 3 hours
  # single letters are sectors: T for land transport, H for building heating,
  # B for biomass supply, I for industry, shipping and aviation
  # solar+c0.5 reduces the capital cost of solar to 50\% of reference value
  # solar+p3 multiplies the available installable potential by factor 3
  # dist{n} includes distribution grids with investment cost of n times cost in data/costs.csv
  # for myopic/perfect foresight cb states the carbon budget in GtCO2 (cumulative
  # emissions throughout the transition path in the timeframe determined by the
  # planning_horizons), be:beta decay; ex:exponential decay
  # cb40ex0 distributes a carbon budget of 40 GtCO2 following an exponential
  # decay with initial growth rate 0 
  planning_horizons : [2030] # investment years for myopic and perfect; or costs year for overnight
  # for example, set to [2020, 2030, 2040, 2050] for myopic foresight

# CO2 budget as a fraction of 1990 emissions
# this is over-ridden if CO2Lx is set in sector_opts
# this is also over-ridden if cb is set in sector_opts
co2_budget:
  2020: 0.7011648746
  2025: 0.5241935484
  2030: 0.2970430108
  2035: 0.1500896057
  2040: 0.0712365591
  2045: 0.0322580645
  2050: 0

# snapshots are originally set in PyPSA-Eur/config.yaml but used again by PyPSA-Eur-Sec
snapshots:
  # arguments to pd.date_range
  start: "2013-01-01" # 2013-01-01 default # turn into wildcard? 
  end: "2014-01-01" # 2014-01-01 default # turn into wildcard? 
  closed: 'left' # end is not inclusive

atlite:
  cutout_dir: '../pypsa-eur/cutouts'
  cutout_name: "europe-2013-era5" # europe-2013-era5 default

# this information is NOT used but needed as an argument for
# pypsa-eur/scripts/add_electricity.py/load_costs in make_summary.py
electricity:
  max_hours:
    battery: 6
    H2: 168

# regulate what components with which carriers are kept from PyPSA-Eur;
# some technologies are removed because they are implemented differently
# or have different year-dependent costs in PyPSA-Eur-Sec
pypsa_eur:
  "Bus": ["AC"]
  "Link": ["DC"]
  "Generator": ["onwind", "offwind-ac", "offwind-dc", "solar", "ror"]
  "StorageUnit": ["PHS","hydro"] # These are the ones which are given by PyPSA-EUR as storage units (not stores) which only has a single variable, p_nom, which is optimized (stores have three: p_nom_charge, p_nom_discharge, E_c))
  "Store": []

biomass:
  year: 2030
  scenario: "Med"
  classes:
    solid biomass: ['Primary agricultural residues', 'Forestry energy residue', 'Secondary forestry residues', 'Secondary Forestry residues sawdust', 'Forestry residues from landscape care biomass', 'Municipal waste']
    not included: ['Bioethanol sugar beet biomass', 'Rapeseeds for biodiesel', 'sunflower and soya for Biodiesel', 'Starchy crops biomass', 'Grassy crops biomass', 'Willow biomass', 'Poplar biomass potential', 'Roundwood fuelwood', 'Roundwood Chips & Pellets']
    biogas: ['Manure biomass potential', 'Sludge biomass']

# only relevant for foresight = myopic or perfect
existing_capacities:
  grouping_years: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019]
  threshold_capacity: 10
  conventional_carriers: ['lignite', 'coal', 'oil', 'uranium']

sector:
  'central' : True
  'central_fraction' : 0.6
  'bev_dsm_restriction_value' : 0.75  #Set to 0 for no restriction on BEV DSM
  'bev_dsm_restriction_time' : 7  #Time at which SOC of BEV has to be dsm_restriction_value
  'transport_heating_deadband_upper' : 20.
  'transport_heating_deadband_lower' : 15.
  'ICE_lower_degree_factor' : 0.375    #in per cent increase in fuel consumption per degree above deadband
  'ICE_upper_degree_factor' : 1.6
  'EV_lower_degree_factor' : 0.98
  'EV_upper_degree_factor' : 0.63
  'district_heating_loss' : 0.15
  'bev_dsm' : True #turns on EV battery
  'bev_availability' : 0.5  #How many cars do smart charging
  'v2g' : False #allows feed-in to grid from EV battery
  #what is not EV or FCEV is oil-fuelled ICE
  'land_transport_fuel_cell_share': 0.15 # 1 means all FCEVs
    # 2020: 0
    # 2030: 0.05
    # 2040: 0.1
    # 2050: 0.15
  'land_transport_electric_share': 0.85 # 1 means all EVs
    # 2020: 0
    # 2030: 0.25
    # 2040: 0.6
    # 2050: 0.85
  'transport_fuel_cell_efficiency': 0.5
  'transport_internal_combustion_efficiency': 0.3
  'shipping_average_efficiency' : 0.4 #For conversion of fuel oil to propulsion in 2011
  'time_dep_hp_cop' : True #time dependent heat pump coefficient of performance
  'heat_pump_sink_T' : 55. # Celsius, based on DTU / large area radiators; used in build_cop_profiles.py
   # conservatively high to cover hot water and space heating in poorly-insulated buildings
  'retrofitting' :
    'retro_exogen': True # space heat demand savings exogenously
    'dE': 0.29 # reduction of space heat demand (applied before losses in DH)
      # 2020 : 0.
      # 2030 : 0.15
      # 2040 : 0.3
      # 2050 : 0.4
    'retro_endogen': False  # co-optimise space heat savings
    'cost_factor' : 1.0
    'interest_rate': 0.04  # for investment in building components
    'annualise_cost': True  # annualise the investment costs
    'tax_weighting': False   # weight costs depending on taxes in countries
    'construction_index': True   # weight costs depending on labour/material costs per ct
    'l_strength': ["0.076", "0.197"] # additional insulation thickness[m], determines number of retro steps(=generators per bus) and maximum possible savings
  'tes' : True
  'tes_tau' : 3.
  'boilers' : True
  'oil_boilers': False
  'chp' : True
  'micro_chp' : False
  'solar_thermal' : True
  'solar_cf_correction': 0.788457  # =  >>> 1/1.2683 # Used for correcting solar thermal CF
  'marginal_cost_storage' : 0. #1e-4
  'methanation' : True
  'helmeth' : True
  'dac' : True
  'home battery': True
  'co2_vent' : True
  'SMR' : True
  'co2_sequestration_potential' : 200  #MtCO2/a sequestration potential for Europe
  'co2_sequestration_cost' : 10   #EUR/tCO2 for transport and sequestration of CO2
  'cc_fraction' : 0.9  # default fraction of CO2 captured with post-combustion capture
  'hydrogen_underground_storage' : False
  'use_fischer_tropsch_waste_heat' : True
  'use_fuel_cell_waste_heat' : False # True
  'electricity_distribution_grid' : False
  'electricity_distribution_grid_cost_factor' : 1.0  #multiplies cost in data/costs.csv
  'electricity_grid_connection' : True  # only applies to onshore wind and utility PV
  'gas_distribution_grid' : True
  'gas_distribution_grid_cost_factor' : 1.0  #multiplies cost in data/costs.csv
  conventional_generation:
    OCGT: gas
    CCGT: gas
    nuclear: uranium
    coal: coal
    # lignite: lignite
    # oil: oil

costs:
  lifetime: 25 #default lifetime
  # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  discountrate: 0.07
  # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html # noqa: E501
  USD2013_to_EUR2013: 0.7532
  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: #
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    battery: 0.

  emission_prices: # only used with the option Ep (emission prices)
    co2: 0.

  lines:
    length_factor: 1.25 #to estimate offwind connection costs

solving:
  tmpdir: 'scratch/$SLURM_JOB_ID'
  options:
    formulation: kirchhoff
    clip_p_max_pu: 1.e-2
    load_shedding: false
    noisy_costs: true
    min_iterations: 1
    max_iterations: 1
    # nhours: 1

  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200

    #FeasibilityTol: 1.e-6

    # name: cplex
    # threads: 4
    # lpmethod: 4 # barrier
    # solutiontype: 2 # non basic solution, ie no crossover
    # barrier_convergetol: 1.e-5
    # feasopt_tolerance: 1.e-6
  mem: 50000 #150000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2

industry:
  'St_primary_fraction' : 0.3 # fraction of steel produced via primary route (DRI + EAF) versus secondary route (EAF); today fraction is 0.6
  'H2_DRI' : 1.7   #H2 consumption in Direct Reduced Iron (DRI),  MWh_H2,LHV/ton_Steel from 51kgH2/tSt in Vogl et al (2018) doi:10.1016/j.jclepro.2018.08.279
  'elec_DRI' : 0.322   #electricity consumption in Direct Reduced Iron (DRI) shaft, MWh/tSt HYBRIT brochure https://ssabwebsitecdn.azureedge.net/-/media/hybrit/files/hybrit_brochure.pdf
  'Al_primary_fraction' : 0.2 # fraction of aluminium produced via the primary route versus scrap; today fraction is 0.4
  'MWh_CH4_per_tNH3_SMR' : 10.8 # 2012's demand from https://ec.europa.eu/docsroom/documents/4165/attachments/1/translations/en/renditions/pdf
  'MWh_elec_per_tNH3_SMR' : 0.7 # same source, assuming 94-6% split methane-elec of total energy demand 11.5 MWh/tNH3
  'MWh_H2_per_tNH3_electrolysis' : 6.5 # from https://doi.org/10.1016/j.joule.2018.04.017, around 0.197 tH2/tHN3 (>3/17 since some H2 lost and used for energy)
  'MWh_elec_per_tNH3_electrolysis' : 1.17 # from https://doi.org/10.1016/j.joule.2018.04.017 Table 13 (air separation and HB)
  'NH3_process_emissions' : 24.5 # in MtCO2/a from SMR for H2 production for NH3 from UNFCCC for 2015 for EU28
  'petrochemical_process_emissions' : 25.5 # in MtCO2/a for petrochemical and other from UNFCCC for 2015 for EU28
  'HVC_primary_fraction' : 1.0 #fraction of current non-ammonia basic chemicals produced via primary route

plotting:
  map:
    figsize: [7, 7]
    boundaries: [-10.2, 29, 35,  72]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3 # 1.e+3  #3.e+3

  costs_max: 250
  costs_threshold: 1

  energy_max: 5000.
  energy_min: -5000.
  energy_threshold: 50.

  vre_techs: ["onwind", "offwind-ac", "offwind-dc", "solar", "ror"]
  renewable_storage_techs: ["PHS","hydro"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["hydro+PHS", "battery", "H2"]
  # store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load"] #, "heat load", "Li ion load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"]
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    "onshore wind" : "#2e8b57"
    "offshore wind" : "#556b2f"
    "offwind-ac" : "#556b2f"
    "offshore wind (AC)" : "#556b2f"
    "offwind-dc" : "#556b2f"
    "offshore wind (DC)" : "#556b2f"
    "solar PV" : "#adff2f"
    "onwind" : "#2e8b57"
    "offwind" : "#556b2f"
    'wind' : "#2e8b57"
    "solar" : "#adff2f"
    "hydro" : "#1e90ff"
    "hydro reservoir" : "#3B5323"
    "ror" : "#78AB46"
    "run of river" : "#78AB46"
    "hydroelectricity" : "#1e90ff" #"#006400"
    "wave" : "#004444"
    "biomass" : "#cd853f"
    "nuclear" : "#b22222"
    "gas" : "#a9a9a9"
    "gas turbine" : "#696969"
    "gas boiler" : "#a9a9a9"
    "oil" : "#696969"
    "coal" : "#555555"
    "lignite" : "#000000"
    "resistive heater" : "#ff8c00"
    "heat pump" : "#ffc34d"
    "hydrogen storage" : "#800080"
    "storage X" : "#800080"
    "X Charge" : "#800080"
    "X Discharge" : "#800080"
    "X Store" : "#800080"
    "battery storage" : "#ffc0cb"
    "hot water storage" : "#ffe0b3"
    "methanation" : "#da70d6"
    "transmission" : "#4d004d"
    "wind and solar" : "#2e8b57"
    "conventional" : "#a9a9a9"
    "balancing" : "#b300b3"
    "power-to-heat" : "#ff8c00"
    "electricity" : "#0000ff"
    "rural heat" : "#ff0000"
    "urban heat" : "#ffa500"
    "cooling" : "#00aecc"
    "waste" : "#804000"
    "gas CHP" : "#f08080"
    "gas CHP elec" : "#f08080"
    "gas CHP heat" : "#f08080"
    "OCGT" : "#000080"
    "CCGT" : "#6495ed"
    "central water tank" : "#daa520"
    "electric vehicle" : "#ff4500"
    "geothermal" : "#804000"
    "district heating" : "#ffe0b3"
    "distribution" : "#cc0066"
    "central gas CHP electric" : "#f08080"
    'solar thermal' : 'coral'
    'solar rooftop' : '#e6b800'
    "OCGT marginal" : "sandybrown"
    "OCGT-heat" : "orange"
    "gas boilers" : "orange"
    "gas boiler marginal" : "orange"
    "gas-to-power/heat" : "orange"
    "natural gas" : "brown"
    "SMR" : "#4F4F2F"
    "oil" : "#B5A642"
    "oil boiler" : "#B5A677"
    "lines" : "k"
    "transmission lines" : "#4d004d"
    "H2" : "m"
    "battery" : "#ffc0cb" #"slategray"
    "home battery" : "#614700"
    "home battery storage" : "#614700"
    "Nuclear" : "#b22222"
    "Nuclear marginal" : "#b22222"
    "uranium" : "#b22222"
    "Coal" : "k"
    "Coal marginal" : "k"
    "Lignite" : "grey"
    "lignite" : "grey"
    "Lignite marginal" : "grey"
    "CCGT" : "orange"
    "CCGT marginal" : "orange"
    "heat pumps" : "#76EE00"
    "heat pump" : "#76EE00"
    "air heat pump" : "#76EE00"
    "ground heat pump" : "#40AA00"
    "resistive heater" : "pink"
    "Sabatier" : "#FF1493"
    "methanation" : "#FF1493"
    "power-to-gas" : "#FF1493"
    "power-to-liquid" : "#FFAAE9"
    "helmeth" : "#7D0552"
    "DAC" : "#E74C3C"
    "co2 stored" : "#123456"
    "CO2 sequestration" : "#123456"
    "CC" : "k"
    "co2" : "#123456"
    "co2 vent" : "#654321"
    "solid biomass for industry co2 from atmosphere" : "#654321"
    "solid biomass for industry co2 to stored": "#654321"
    "gas for industry co2 to atmosphere": "#654321"
    "gas for industry co2 to stored": "#654321"
    "Fischer-Tropsch" : "#44DD33"
    "kerosene for aviation": "#44BB11"
    "naphtha for industry" : "#44FF55"
    "land transport oil" : "#44DD33"
    "water tanks" : "#BBBBBB"
    "hot water storage" : "#BBBBBB"
    "hot water charging" : "#BBBBBB"
    "hot water discharging" : "#999999"
    "CHP" : "r"
    "CHP heat" : "r"
    "CHP electric" : "r"
    "PHS" : "#1e90ff" #"g"
    "Ambient" : "k"
    "Electric load" : "b"
    "Heat load" : "r"
    "heat" : "darkred"
    "rural heat" : "#880000"
    "central heat" : "#b22222"
    "decentral heat" : "#800000"
    "low-temperature heat for industry" : "#991111"
    "process heat" : "#FF3333"
    "heat demand" : "darkred"
    "electric demand" : "k"
    "Li ion" : "grey"
    "retrofitting" : "purple"
    "building retrofitting" : "purple"
    "BEV charger" : "grey"
    "V2G" : "grey"
    "land transport EV" : "grey"
    "electricity" : "k"
    "gas for industry" : "#333333"
    "solid biomass for industry" : "#555555"
    "industry electricity" : "#222222"
    "industry new electricity" : "#222222"
    "process emissions to stored" : "#444444"
    "process emissions to atmosphere" : "#888888"
    "process emissions" : "#222222"
    "oil emissions" : "#666666"
    "land transport fuel cell" : "#AAAAAA"
    "biogas" : "#800000"
    "solid biomass" : "#DAA520"
    "today" : "#D2691E"
    "shipping" : "#6495ED"
    "electricity distribution grid" : "#333333"
  nice_names:
    # OCGT: "Gas"
    # OCGT marginal: "Gas (marginal)"
    offwind: "offshore wind"
    onwind: "onshore wind"
    battery: "Battery storage"
    lines: "Transmission lines"
    AC line: "AC lines"
    AC-AC: "DC lines"
    ror: "Run of river"
  nice_names_n:
    offwind: "offshore\nwind"
    onwind: "onshore\nwind"
    # OCGT: "Gas"
    H2: "Hydrogen\nstorage"
    # OCGT marginal: "Gas (marginal)"
    lines: "transmission\nlines"
    ror: "run of river"
